### PR TITLE
add Refactor Code plugin

### PR DESCRIPTION
**Pull request by CharsDavy**
refactor some method style, such as setter

### CODE REVIEW

**Comment by jurre** [comment]
You've added it as a `file_template`, it looks like this is a plugin so it should go under the `plugins` key in the JSON file.

**Comment by CharsDavy** [comment]
I had added the key "Refactor Code" in the JSON file.

**Comment by jurre** [comment]
> The JSON file is split up into 4 different parts: `plugins`, `file_templates`, `color_schemes` and `project_templates`. Make sure to add your package to the right category or it won't install.

Your plugin is listed under `file_templates` and it should be under `plugins`. It will not work this way

**Comment by CharsDavy** [comment]
I'm so sorry. I have added the content in file_templates and plugins key.

**Comment by jurre** [comment]
Great, now it just needs to be removed from `color_schemes`

**Comment by CharsDavy** [comment]
I had added the "Refactor Code" and its some infomation in only 'plugins' and 'file_templates' key.

**Comment by jurre** [comment]
Oh, they are different projects! Maybe we could give the file_templates one a different name? Like `Refactor Code File Templates` to make it clear they're not the same? If you'd prefer to keep them the same let me know and I'll go ahead and merge it

**Comment by CharsDavy** [comment]
I just want to submit plugin "Refactor Code". I can remove "Refactor Code" from 'file_templates' key?Thanks

**Comment by CharsDavy** [comment]
I just want to submit plugin,so I remove the "Refactor Code" from file_templates, color_schemes and project_templates. And I know yours JSON file work now.Thanks very much.

**Pull request merged**
