### PR TITLE
Update packages.json

### PR DESCRIPTION
**Pull request by DevDu**
add fastCoding

### CODE REVIEW

**Comment by DevDu** [comment]
why?

**Comment by guillaume-algis** [comment]
The CI failed because the screenshot URL you included is not a direct link to the image, but a link to the github page displaying the image.

The correct URL is `https://raw.githubusercontent.com/DevDu/FastCoding-Xcode-Plugin/master/screenshot/screenShot1.gif`

**Comment by DevDu** [comment]
Now I'm going to replace PNG with GIF, and now it's the right link, before it's possible that GIF is too big.

**Comment by guillaume-algis** [comment]
Thank you. Could you rebase on top of `master` so we can merge this, please?

**Comment by DevDu** [comment]
Now, you see, I have two tips below the status of the green, I have merged branches, all through the future when I can search, thank you

**Comment by guillaume-algis** [comment]
Thank you, looks good 👍

**Pull request merged**
