### PR TITLE
Add "HCTemplet" plugin

### PR DESCRIPTION
**Pull request by dongjiali**
Add "HCTemplet" plugin

### CODE REVIEW

**Comment by guillaume-algis** [comment]
The JSON file is split up into 4 different parts: plugins, file_templates, color_schemes and project_templates. You've added this as a project template, it should go under the `plugins` key.

**Comment by dongjiali** [comment]
add HCTemplet to  plugins key.

**Comment by guillaume-algis** [comment]
Still not good @dongjiali, you moved it to the `project_templates`, we need this to be in the `plugins` section.

**Comment by dongjiali** [comment]
moved it to the plugins section

**Comment by guillaume-algis** [comment]
👍 

@jurre, I can't merge things in alcatraz-packages, could you take care of this please? Thanks!

**Comment by jurre** [comment]
Done, and you should be able to merge stuff here now!

**Comment by guillaume-algis** [comment]
Yep, thank you 🙌

**Pull request merged**
