### PR TITLE
RainyCode plugin

### PR DESCRIPTION
**Pull request by dimohamdy**
add RainyCode plugin

### CODE REVIEW

**Comment by jurre** [comment]
You've added this as a file template but it looks like it should be under `plugins`, could you move it there, otherwise the install won't work for people

**Comment by guillaume-algis** [comment]
@jurre looks fine to me :)

**Comment by dimohamdy** [comment]
it's the object number 131 under plugin array in json
http://www.jsoneditoronline.org/?id=ff63168ac09f228cd24bfcb986399082

**Comment by jurre** [comment]
Oh then `RealmPlugin` is actually in the wrong place, my bad!

**Pull request merged**
