### PR TITLE
Add plugin ESTraslate to Alcatraz

### PR DESCRIPTION
**Pull request by EnjoySR**
Add plugin ESTraslate to Alcatraz.
helps you translation of Xcode words quickly.

repo: [https://github.com/EnjoySR/ESTranslate-Xcode](https://github.com/EnjoySR/ESTranslate-Xcode)

Thanks!

### CODE REVIEW

**Comment by jurre** [comment]
Why did you close the PR?

**Comment by EnjoySR** [comment]
I thought I cannot pass...😥

**Comment by jurre** [comment]
Just needs a rebase against master and we can merge it!

**Comment by EnjoySR** [comment]
uh..What should I do?

**Comment by jurre** [comment]
I don't think these changes include the ESTranslate plugin now? I don't get the diff

**Comment by EnjoySR** [comment]
@jurre What's the problem? I need make PR again?

**Pull request merged**
