### PR TITLE
a new Xcode plugin: FastStub

### PR DESCRIPTION
**Pull request by music4kid**
:)

### CODE REVIEW

**Comment by jurre** [comment]
Why was XcodeFolders removed?

**Comment by music4kid** [comment]
sorry, my bad, I accidentally deleted it. shall I submit another one?

**Comment by jurre** [comment]
Doesn't have to be a separate PR, but the JSON file is split up into 4 different parts: `plugins`, `file_templates`, `color_schemes` and `project_templates`. You've added this as a project template, it should go under the `plugins` key.

**Comment by music4kid** [comment]
Thanks, jurre.

**Pull request closed without merging**
