### PR TITLE
submit ProjectCleaner

### PR DESCRIPTION
**Pull request by Lobster-King**
submit ProjectCleaner

### CODE REVIEW

**Comment by Lobster-King** [comment]
submit ProjectCleaner

**Comment by Lobster-King** [comment]
Submit

**Comment by jurre** [comment]
Thanks

**Comment by Lobster-King** [comment]
Thank you very much 


发自 网易邮箱大师
On 07/20/2016 17:36, Jurre wrote:

Merged #604.

**Pull request merged**
