### PR TITLE
modify description and add the link to the plugin Alcatraz

### PR DESCRIPTION
**Pull request by niehaili**

### CODE REVIEW

**Comment by jurre** [comment]
Installing Alcatraz with Alcatraz wouldn't really make sense, because then you'd already have it installed right? :)

**Comment by niehaili** [comment]
I think the main purpose is to delete

**Comment by guillaume-algis** [comment]
- Regarding the description of your plugin, I think it's more idiomatic to begin with `option` and then `shift` (see screenshot), but I'm nitpicking, and it's your plugin so your call.
- Regarding adding Alcatraz to the list of plugins, it should at least been a separate PR so we can discuss the pros and cons. The removal procedure is described on http://alcatraz.io/, I'm not convinced there's a use case for desinstalling Alcatraz from its own interface.

**Comment by niehaili** [comment]
Oh,I see,thank you very much!! I will resubmit it once again.

**Pull request closed without merging**
