### PR TITLE
Add a new Xcode plugin.

### PR DESCRIPTION
**Pull request by red3**
I add a new Xcode plugin which helps people generate JsonModel Mapper automatically.

### CODE REVIEW

**Comment by red3** [comment]
The Travis CI build logs this:
ERROR:  Error installing json:
	json requires Ruby version ~> 2.0.

Is there something wrong with my merge?

**Comment by guillaume-algis** [comment]
@red3 nope, nothing wrong, the CI was broken at the time of your commit. The build passed with Ruby 2 though, so we're good.

Thanks!

**Comment by red3** [comment]
@guillaume-algis rebased yet. And this time there are no build errors, good to see that!

**Comment by guillaume-algis** [comment]
Thank you!

**Pull request merged**
