### PR TITLE
Add Anglerfish plugin

### PR DESCRIPTION
**Pull request by dealforest**

### CODE REVIEW

**Comment by guillaume-algis** [comment]
The JSON file is split up into 4 different parts: plugins, file_templates, color_schemes and project_templates. You've added this as a project template, it should go under the `plugins` key.

**Comment by dealforest** [comment]
oops :bow:
I fixed it.

**Comment by jurre** [comment]
Thanks!

**Comment by dealforest** [comment]
Thanks 🎉

**Pull request merged**
