### PR TITLE
add Xcode plugin

### PR DESCRIPTION
**Pull request by lhhuai**
Quick Show In Finder

A Xcode Plugin to quick show in finder with using shortcut key（alt+f）.

### CODE REVIEW

**Comment by jurre** [comment]
You've added it under `file_templates`, looks like it should be under `plugins`

**Comment by lhhuai** [comment]
I'll want to add my plugin into packages.json, I don't search it in packages.json(alcatraz/alcatraz-packages). Please help me check. My goal is that my plugin can be found in Package Manager. Thanks.

**Comment by jurre** [comment]
The plugin is in the wrong section right now, please update your pull request so it is added under the `plugins` key in the json file, otherwise it won't work

**Comment by lhhuai** [comment]
Could I please re submit a new pull request? You directly cancel the previous pull request.

**Comment by jurre** [comment]
Eh yeah sure :)

**Comment by lhhuai** [comment]
Has been re submited, please help me to deal with it(Add QuickShowInFinder Plugin #456), thks.

**Pull request closed without merging**
